output_folder_name = "output_data"
output_path = rf"C:\Users\Rohit\Desktop\ai_nexus\data_segregation_param_city"
input_folder_path = r"C:\Users\Rohit\Desktop\ai_nexus\data_segregation_param_city\input_data"
input_daily_files = r"daily_files"
input_others_files = r"others"
input_processed_files = r"processed"